### ISSUE TITLE
Copyright in LICENSE incorrect

### ISSUE THREAD

**Issue by gnewton** [AAFC-MBB/gflow#2]
Instead of:
 Copyright (c) 2015 Microbial Biodiversity Bioinformatics @ Agriculture and Agri-Food Canada

should be:
  Copyright (c) 2015 Government of Canada

Reference example: http://wet-boew.github.io/wet-boew/License-en.html

**Comment by oxyko** [comment]
Good catch, Glen. I'll bring it up at the code review tomorrow. Wanna join us :)?

**Comment by gnewton** [comment]
Not able to  :-(

**Comment by alexjsmac** [comment]
Yes thanks Glen! Fixed in 98a56feb9db5b0d1e7a7a8ba85451c3df44ddb1b
